/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luisf
 */
import javax.swing.JOptionPane;

public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbMoeda1 = new javax.swing.JComboBox<>();
        cbMoeda2 = new javax.swing.JComboBox<>();
        ctMoeda1 = new javax.swing.JTextField();
        btConverter = new javax.swing.JButton();
        ctMoeda2 = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Moedas");

        cbMoeda1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Real", "Dólar", "Euro", "Libra", "Iene" }));
        cbMoeda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMoeda1ActionPerformed(evt);
            }
        });

        cbMoeda2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dólar", "Real", "Euro", "Libra", "Iene" }));

        btConverter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConverter.setText("Converter");
        btConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConverterActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cbMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ctMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(ctMoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbMoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConverter)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctMoeda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctMoeda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConverter)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConverterActionPerformed
       converter();
    }//GEN-LAST:event_btConverterActionPerformed

    private void cbMoeda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMoeda1ActionPerformed
        
    }//GEN-LAST:event_cbMoeda1ActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    public void limpar() {
        ctMoeda1.setText("");
        ctMoeda2.setText("");
    }
    
    public void converter() {
        Moeda moeda1 = new Moeda();
        Moeda moeda2 = new Moeda();
        
        if(cbMoeda1.getSelectedIndex() == 0) {
            switch(cbMoeda2.getSelectedIndex()) {
                case 0:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 5.22));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 1:
                    JOptionPane.showMessageDialog(null, "Erro!!! Escolha uma moeda diferente para realizar a conversao", "Conversao", 0);
                    break;
                case 2:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 5.55));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 3:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 6.28));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 4:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 25.88));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
            }
        }
        
        if(cbMoeda1.getSelectedIndex() == 1) {
            switch(cbMoeda2.getSelectedIndex()) {
                case 0:
                    JOptionPane.showMessageDialog(null, "Erro!!! Escolha uma moeda diferente para realizar a conversao", "Conversao", 0);
                    break;
                case 1:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.19));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 2:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.94));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 3:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.83));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 4:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 135.02));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
            }
        }
        
        if(cbMoeda1.getSelectedIndex() == 2) {
            switch(cbMoeda2.getSelectedIndex()) {
                case 0:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 1.06));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 1:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 5.55));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 2:
                    JOptionPane.showMessageDialog(null, "Erro!!! Escolha uma moeda diferente para realizar a conversao", "Conversao", 0);
                    break;
                case 3:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.88));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 4:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 143.87));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
            }
        }
        
        if(cbMoeda1.getSelectedIndex() == 3) {
            switch(cbMoeda2.getSelectedIndex()) {
                case 0:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 1.20));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 1:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 6.28));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 2:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 1.13));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 3:
                    JOptionPane.showMessageDialog(null, "Erro!!! Escolha uma moeda diferente para realizar a conversao", "Conversao", 0);
                    break;
                case 4:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 162.48));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
            }
        }
        
        if(cbMoeda1.getSelectedIndex() == 4) {
            switch(cbMoeda2.getSelectedIndex()) {
                case 0:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.0074));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 1:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.039));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 2:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.0070));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 3:
                    moeda1.setValor(Float.parseFloat(ctMoeda1.getText()));
                    moeda2.setValor((float)(moeda1.getValor() * 0.0062));
                    ctMoeda2.setText(String.valueOf(moeda2.getValor()));
                    JOptionPane.showMessageDialog(null, "Valor Convertido com Sucesso!!!", "Coversao", 1);
                    break;
                case 4:
                   JOptionPane.showMessageDialog(null, "Erro!!! Escolha uma moeda diferente para realizar a conversao", "Conversao", 0);
                   break;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConverter;
    private javax.swing.JButton btLimpar;
    private javax.swing.JComboBox<String> cbMoeda1;
    private javax.swing.JComboBox<String> cbMoeda2;
    private javax.swing.JTextField ctMoeda1;
    private javax.swing.JTextField ctMoeda2;
    // End of variables declaration//GEN-END:variables
}
